version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: satransportes
    ports:
      - "3306:3306"
    command: ["mysqld", "--bind-address=0.0.0.0", "--user=root", "--default-authentication-plugin=mysql_native_password"]