<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TipoDeSolicitacaoDeAlteracao extends Model
{
    protected $fillable = [
        'nome',
        'nome_campo1',
        'nome_campo2',
        'nome_campo3',
        'nome_campo4',
        'nome_campo5',
        'nome_campo6',
        'nome_campo7',
        'nome_campo8',
        'nome_campo9',
        'nome_campo10',
        'nome_campo11',
        'nome_campo12',
        'nome_campo13',
        'nome_campo14',
        'nome_campo15',
        'nome_campo16',
        'nome_campo17',
        'nome_campo18',
        'nome_campo19',
        'nome_campo20',
        'nome_campo21',
        'nome_campo22',
        'nome_campo23',
        'nome_campo24',
        'nome_campo25',
        'desc_campo1',
        'desc_campo2',
        'desc_campo3',
        'desc_campo4',
        'desc_campo5',
        'desc_campo6',
        'desc_campo7',
        'desc_campo8',
        'desc_campo9',
        'desc_campo10',
        'desc_campo11',
        'desc_campo12',
        'desc_campo13',
        'desc_campo14',
        'desc_campo15',
        'desc_campo16',
        'desc_campo17',
        'desc_campo18',
        'desc_campo19',
        'desc_campo20',
        'desc_campo21',
        'desc_campo22',
        'desc_campo23',
        'desc_campo24',
        'desc_campo25',
        'regex_campo1',
        'regex_campo2',
        'regex_campo3',
        'regex_campo4',
        'regex_campo5',
        'regex_campo6',
        'regex_campo7',
        'regex_campo8',
        'regex_campo9',
        'regex_campo10',
        'regex_campo11',
        'regex_campo12',
        'regex_campo13',
        'regex_campo14',
        'regex_campo15',
        'regex_campo16',
        'regex_campo17',
        'regex_campo18',
        'regex_campo19',
        'regex_campo20',
        'regex_campo21',
        'regex_campo22',
        'regex_campo23',
        'regex_campo24',
        'regex_campo25',
        'desc_arquivo1',
        'desc_arquivo2',
        'desc_arquivo3',
        'desc_arquivo4',
    ];

    protected $table = 'tipos_solicitacao_de_alteracao';

    ///////////////////


}
